name: MLflow CI Retrain and Docker Build

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  retrain:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          pip install mlflow==2.19.0 scikit-learn pandas numpy

      - name: Run MLflow Project
        working-directory: ./Workflow-CI/MLProject
        run: |
          echo "=== Running MLflow Project ==="
          ls -la
          mlflow run . --env-manager local

      - name: Upload MLflow artifacts
        uses: actions/upload-artifact@v4
        with:
          name: mlruns
          path: Workflow-CI/MLProject/mlruns/

  docker:
    needs: retrain
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download artifacts from retrain job
        uses: actions/download-artifact@v4
        with:
          name: mlruns
          path: Workflow-CI/MLProject/mlruns/

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install MLflow and dependencies
        run: |
          pip install mlflow==2.19.0 scikit-learn pandas numpy

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        working-directory: ./Workflow-CI/MLProject
        run: |
          RUN_ID=$(ls -td mlruns/0/*/ | head -1 | xargs -n 1 basename)
          echo "Detected latest run ID: $RUN_ID"
          mlflow models build-docker -m "mlruns/0/$RUN_ID/artifacts/model" -n eka-fanya-model
          docker tag eka-fanya-model ${{ secrets.DOCKERHUB_USERNAME }}/eka-fanya-model:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/eka-fanya-model:latest
