name: MSML CI Workflow

on:
  push:
    branches: [ "main" ]
    paths:
      - 'Workflow-CI/MLProject/**'
      - 'Workflow-CI/MLProject/modelling.py'
  workflow_dispatch:

jobs:
  retrain:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          pip install mlflow==2.19.0 scikit-learn==1.6.1 pandas numpy

      - name: Run MLflow project
        run: |
          mlflow run Workflow-CI/MLProject --env-manager local

      - name: Upload mlruns artifact
        uses: actions/upload-artifact@v4
        with:
          name: mlruns
          path: Workflow-CI/MLProject/mlruns

  docker:
    runs-on: ubuntu-latest
    needs: retrain

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download mlruns artifact
        uses: actions/download-artifact@v4
        with:
          name: mlruns
          path: Workflow-CI/MLProject/mlruns

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install MLflow and dependencies
        run: |
          pip install mlflow==2.19.0 scikit-learn==1.6.1 pandas numpy

      - name: Login to Docker Hub
        run: |
          echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Build and push Docker image
        run: |
          echo "üîç Listing model runs..."
          ls Workflow-CI/MLProject/mlruns || true
          MODEL_PATH=$(find Workflow-CI/MLProject/mlruns -type f -name model.pkl | head -n 1)
          echo "Model path: $MODEL_PATH"
          mlflow models build-docker -m $(dirname $MODEL_PATH) -n msml_fanya_model
          docker push msml_fanya_model
